/// Flutter icons CustomeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomeIcons
///      fonts:
///       - asset: fonts/CustomeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomeIcons {
  CustomeIcons._();

  static const _kFontFam = 'CustomeIcons';

  static const IconData coffee_cup = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shuttle = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData washing_machine = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData taxi = const IconData(0xe803, fontFamily: _kFontFam);
}
